"""Guards the plugin directory's shape — the failure that cost a live channel once.

Everything else here tests behaviour; this file tests packaging, because the directory layout is what
Hermes's plugin manager reads when it decides whether a plugin is installable.
"""

from __future__ import annotations

import pathlib

PLUGIN_DIR = pathlib.Path(__file__).resolve().parents[1]


def test_plugin_dir_carries_no_packaging_manifest():
    """A manifest here makes Hermes treat the plugin as a package and can disable it outright.

    ``pm/plugin_declarations.py`` copies any plugin dir holding a ``pyproject.toml`` (without the marker
    "GENERATED by pm") into ``plugin-sources/<key>/`` and runs ``uv lock``. With no ``[project].name`` /
    ``version`` that fails, and ``hermes update`` adds the plugin to ``plugins.disabled`` — a live channel
    went dark for 13 minutes exactly this way. Test config belongs in ``pytest.ini``, which PM never inspects.
    """
    offenders = [n for n in ("pyproject.toml", "setup.py", "setup.cfg") if (PLUGIN_DIR / n).exists()]
    assert not offenders, (
        f"packaging manifest(s) in {PLUGIN_DIR} would disable the plugin on the next `hermes update`: {offenders}"
    )
    assert (PLUGIN_DIR / "pytest.ini").is_file(), "test config must live in pytest.ini (see docstring)"


def test_package_load_failures_stay_loud_instead_of_degrading_to_none():
    """The tolerance in ``__init__.py`` must cover ONLY the bare-module load.

    A blanket ``try/except ImportError`` would also swallow a genuine failure on the loader's path:
    the plugin would import cleanly and register nothing — much worse than an error at startup. This
    pins the difference using a dying ``adapter.py`` next to a copy of the real ``__init__.py``.
    """
    import importlib.util
    import shutil
    import tempfile

    staging = pathlib.Path(tempfile.mkdtemp(prefix="vk-dying-adapter-"))
    try:
        (staging / "__init__.py").write_text(
            (PLUGIN_DIR / "__init__.py").read_text(encoding="utf-8"), encoding="utf-8")
        (staging / "adapter.py").write_text("raise ImportError('adapter is broken')\n", encoding="utf-8")
        spec = importlib.util.spec_from_file_location(
            "hermes_plugins.platforms__vk", staging / "__init__.py",
            submodule_search_locations=[str(staging)])
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        try:
            spec.loader.exec_module(module)
        except ImportError:
            pass  # loud, as required
        else:
            raise AssertionError(f"a broken adapter was swallowed: register={module.register!r}")
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def test_init_loads_as_a_package_and_stays_importable_as_a_bare_module():
    """``__init__.py`` must serve two callers with opposite needs.

    Hermes' loader imports this directory as a package, so ``register`` must be the real function here.
    pytest instead resolves a checkout's package by importing the root ``__init__.py`` directly when the
    directory name is not a valid identifier — a plain ``git clone`` lands in ``hermes-vk`` — where a
    relative import cannot resolve; that path must not break collection (33 collection errors before the
    shim existed).
    """
    import importlib.util

    import vk

    assert callable(vk.register), "the package load must expose the real register()"

    spec = importlib.util.spec_from_file_location("__init__", PLUGIN_DIR / "__init__.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # must not raise
    assert module.register is None, "a bare module load has nothing to register"
