"""Guards the plugin directory's shape — the failure that cost a live channel once.

Everything else here tests behaviour; this file tests packaging, because the directory layout is what
Hermes's plugin manager reads when it decides whether a plugin is installable.
"""

from __future__ import annotations

import pathlib

PLUGIN_DIR = pathlib.Path(__file__).resolve().parents[1]


def test_plugin_dir_carries_no_packaging_manifest():
    """A manifest here makes Hermes treat the plugin as a package and can disable it outright.

    ``pm/plugin_declarations.py`` copies any plugin dir holding a ``pyproject.toml`` (without the marker
    "GENERATED by pm") into ``plugin-sources/<key>/`` and runs ``uv lock``. With no ``[project].name`` /
    ``version`` that fails, and ``hermes update`` adds the plugin to ``plugins.disabled`` — a live channel
    went dark for 13 minutes exactly this way. Test config belongs in ``pytest.ini``, which PM never inspects.
    """
    offenders = [n for n in ("pyproject.toml", "setup.py", "setup.cfg") if (PLUGIN_DIR / n).exists()]
    assert not offenders, (
        f"packaging manifest(s) in {PLUGIN_DIR} would disable the plugin on the next `hermes update`: {offenders}"
    )
    assert (PLUGIN_DIR / "pytest.ini").is_file(), "test config must live in pytest.ini (see docstring)"
